### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by nt1m** [reesmichael1/The-History-Panel#7]
Firefox now supports chrome extensions + opera's sidebar API. It should be easily possible to port this to Firefox.

**Comment by reesmichael1** [comment]
Hey, thanks for pointing this out--I'll look into it!

**Comment by reesmichael1** [comment]
@nt1m Sorry it took so long, but I just submitted it for review!

**Comment by reesmichael1** [comment]
Done, thanks again for the suggestion!

https://addons.mozilla.org/addon/the-history-panel/

**Comment by nt1m** [comment]
This is awesome, thanks!
